name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev


jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


  push_to_registry:
    name: Push to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' # Samo za 'dev' branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '16'

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/upravljanje-prostorov:latest
          labels: ${{ secrets.DOCKER_USERNAME }}/upravljanje-prostorov:latest

  deploy_to_azure:
    name: Deploy to Azure
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Samo za 'main' branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        run: az login

      - name: Set AKS context
        run: az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_CLUSTER_NAME }}

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v1
        with:
          manifests: k8s/upravljanje-prostorov-deployment.yaml
          images: jantopolovec/upravljanje-prostorov:latest